// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmiHNkhJRcA42_ijwEidQgtfzbOGm6Vo',
    appId: '1:285088943630:web:79742b68a88e8d4137f65f',
    messagingSenderId: '285088943630',
    projectId: 'tahir1002-8acc5',
    authDomain: 'tahir1002-8acc5.firebaseapp.com',
    databaseURL: 'https://tahir1002-8acc5-default-rtdb.firebaseio.com',
    storageBucket: 'tahir1002-8acc5.firebasestorage.app',
    measurementId: 'G-01PFEK4PPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-2wAOLFXmUpvZWOQq4lYC8ENOjNGnxg',
    appId: '1:285088943630:android:22ac3a32693a93e937f65f',
    messagingSenderId: '285088943630',
    projectId: 'tahir1002-8acc5',
    databaseURL: 'https://tahir1002-8acc5-default-rtdb.firebaseio.com',
    storageBucket: 'tahir1002-8acc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzHVSt6RQlab_kYB4bSFgyIVOd4etX62w',
    appId: '1:285088943630:ios:0f28f7259b59c94837f65f',
    messagingSenderId: '285088943630',
    projectId: 'tahir1002-8acc5',
    databaseURL: 'https://tahir1002-8acc5-default-rtdb.firebaseio.com',
    storageBucket: 'tahir1002-8acc5.firebasestorage.app',
    iosBundleId: 'com.example.empathyTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzHVSt6RQlab_kYB4bSFgyIVOd4etX62w',
    appId: '1:285088943630:ios:0f28f7259b59c94837f65f',
    messagingSenderId: '285088943630',
    projectId: 'tahir1002-8acc5',
    databaseURL: 'https://tahir1002-8acc5-default-rtdb.firebaseio.com',
    storageBucket: 'tahir1002-8acc5.firebasestorage.app',
    iosBundleId: 'com.example.empathyTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtmiHNkhJRcA42_ijwEidQgtfzbOGm6Vo',
    appId: '1:285088943630:web:5f3c2b7252ca7c8137f65f',
    messagingSenderId: '285088943630',
    projectId: 'tahir1002-8acc5',
    authDomain: 'tahir1002-8acc5.firebaseapp.com',
    databaseURL: 'https://tahir1002-8acc5-default-rtdb.firebaseio.com',
    storageBucket: 'tahir1002-8acc5.firebasestorage.app',
    measurementId: 'G-F19LHRF3YL',
  );
}
